# Generated by Django 3.1.5 on 2021-04-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='fistParagraph',
            new_name='firstParagraph',
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.URLField(),
        ),
    ]
